### ISSUE TITLE
Cannot execute sign on Linux runners

### ISSUE THREAD

**Issue by timheuer** [NuGet/setup-nuget#5] opened 2019-12-16 20:10 UTC
When trying to sign a package using a linux runner (`ubuntu-latest`) the action fails with certificate chain validation errors:
```
NU3018: PartialChain
WARNING: NU3018: RevocationStatusUnknown
WARNING: NU3018: OfflineRevocation
NU3018: Certificate chain validation failed.
NuGet.Packaging.Signing.SignatureException: Certificate chain validation failed.
  at NuGet.Packaging.Signing.CertificateChainUtility.GetCertificateChain (System.Security.Cryptography.X509Certificates.X509Certificate2 certificate, System.Security.Cryptography.X509Certificates.X509Certificate2Collection extraStore, NuGet.Common.ILogger logger, NuGet.Packaging.Signing.CertificateType certificateType) [0x00199] in <ff502667b3fe4a85827635c6fe6b0d0d>:0 
  at NuGet.Packaging.Signing.SignPackageRequest.BuildSigningCertificateChainOnce (NuGet.Common.ILogger logger) [0x00018] in <ff502667b3fe4a85827635c6fe6b0d0d>:0 
  at NuGet.Packaging.Signing.SigningUtility.Verify (NuGet.Packaging.Signing.SignPackageRequest request, NuGet.Common.ILogger logger) [0x000a7] in <ff502667b3fe4a85827635c6fe6b0d0d>:0 
  at NuGet.Commands.SignCommandRunner.ExecuteCommandAsync (System.Collections.Generic.IEnumerable`1[T] packagesToSign, NuGet.Packaging.Signing.SignPackageRequest signPackageRequest, System.String timestamper, NuGet.Common.ILogger logger, System.String outputDirectory, System.Boolean overwrite, System.Threading.CancellationToken token) [0x00014] in <ff502667b3fe4a85827635c6fe6b0d0d>:0
```

When switching to `windows-latest` runner agent the same sign command works fine.

**Comment by zkat** [comment] 2019-12-17 17:21
For the record, this is being worked on right now: https://github.com/NuGet/Home/issues/8593

**Comment by zkat** [comment] 2019-12-17 17:22
I'm going to close this issue because this is a NuGet bug, not a bug with the action itself. Please follow the above ticket if you're interested in when this feature will be available.

**Closed by zkat** 2019-12-17 17:22 UTC

**Comment by mwpowellhtx** [comment] 2024-03-29 18:39
Latest `nuget.exe` trying to sign.

```
WARNING: NU3018: RevocationStatusUnknown: The revocation function was unable to check revocation for the certificate.
```

For my own edification, what specs should I relay to signing? And/or how should we best specify our certs, SHA, etc?

We are using XCA, for instance, to run our CA internally.
