### ISSUE TITLE
GutHub action fails on set-env command

### ISSUE THREAD

**Issue by tdriver** [NuGet/setup-nuget#33] opened 2021-10-05 20:09 UTC
Github no longer supports the set-env command as they are insecure. When using this package in a GitHub action, this error is generated:

> Error: Unable to process command '##[set-env name=NUGET;]C:\hostedtoolcache\windows\nuget.exe\5.11.0\x64/nuget.exe' successfully.

A workaround is to enable insecure commands (ACTIONS_ALLOW_UNSECURE_COMMANDS = true), but this is still insecure.

This package should be updated to use the new Env files as Github recommends (https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#environment-files)

**Comment by iPipelineMK** [comment] 2021-12-08 13:45
This appears to be fixed in the 1.0.5 release: https://github.com/marketplace/actions/setup-nuget-exe-for-use-with-actions

**Comment by jeffkl** [comment] 2022-04-06 18:35
Closing this as it appears to be fixed, please re-open if the problem is still occurring with the latest version.

**Closed by jeffkl** 2022-04-06 18:35 UTC
